### ISSUE TITLE
Registering a post route

### ISSUE THREAD

**Issue by nicholasoxford** [galvez/fastify-vite#3]
I am trying to have a better understanding  of server.js and Fastify in general..  I'm sure I am missing something obvious, but I can't seem to get this to work. And often receive the error message. 

`AssertionError [ERR_ASSERTION]: The first character of a path should be `/` or `*``

Furthermore, lets say in nuxt I used fetch() to do

```
await fetch(
      'https://us-east-1.aws.realm.mongodb.com/api/client/v2.0/app/dream-hfcur/graphql',
      requestOptions
    )
      .then((response) => response.json())
      .then((data) =>
        data.data.images.forEach((x) =>
          this.imgData.push({
            url: x.url.replace('.tiff', '.jpeg'),
            title: x.title,
          })
        )
      )
```
Request options being:

```
const requestOptions = {
  method: 'POST',
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Content-Type': 'application/json',
    apiKey: 'ApiKey'
  },
  body: JSON.stringify({
    query: 'query { images(sortBy: _ID_DESC) { _id title url }}'
  })
}
```
1. I should do the data formatting in the reply({}), yes?

 2. I had to add a proxy to nuxt.config.js for my graphql route because of CORS issues, will I have to do the same?

I've added the following code to server.js

```
const requestOptions = {
  method: 'POST',
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Content-Type': 'application/json',
    apiKey: 'ApiKey'
  },
  body: JSON.stringify({
    query: 'query { images(sortBy: _ID_DESC) { _id title url }}'
  })
}
```

```
const requestOptions = {
  method: 'POST',
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Content-Type': 'application/json',
    apiKey: 'ApiKey'
  },
  body: JSON.stringify({
    query: 'query { images(sortBy: _ID_DESC) { _id title url }}'
  })
}
```

`fastify.post('/*', fastify.vite.handler)`

3. What do I need to add to server.js to have this working let fetch?

BTW this is so cool. I was so interested in Fastly, so to have this pushed me over the edge to dive deep.

**Comment by galvez** [comment]
> I should do the data formatting in the reply({}), yes?

For using reusable API methods ([`fastify-api`](https://github.com/galvez/fastify-api), yes, use `reply.send()`.

> I had to add a proxy to nuxt.config.js for my graphql route because of CORS issues, will I have to do the same?

For this you can use [`fastify-reply-from`](https://github.com/fastify/fastify-reply-from), it's **very fast**.

> What do I need to add to server.js to have this working let fetch?

I'm not really sure what is the question -- check out [`fastify-vite-vue-hackernews`](https://github.com/galvez/fastify-vite-vue-hackernews) for a more complete example. Or share your repo with me with some more comments on what you're trying to achieve and maybe I can help out real quick.
